site_name: QuecPython
site_url: https://python.quectel.com/wiki
repo_url: https://github.com/quecpython/wiki
edit_uri: edit/main/docs/
copyright: quectel

nav:
    - QuecPython:
        - Python基础: python/index.md
        - QuecPython API说明: api.md
        - QuecPython 理论学习: study/zh-cn/study/QuecPythonTheory.md
        - QuecPython 驱动子系统:
            - 平台驱动开发:
                - QuecPython RTC开发: study/zh-cn/study/QuecPythonSub/RTC.md
                - QuecPython Timer定时器开发: study/zh-cn/study/QuecPythonSub/Timer.md            
                - QuecPython Watchdog开发: study/zh-cn/study/QuecPythonSub/WDT.md
                - QuecPython Power开关机开发: study/zh-cn/study/QuecPythonSub/Power.md 
                - QuecPython 低功耗开发: study/zh-cn/study/QuecPythonSub/PM.md
                - QuecPython 充电管理: study/zh-cn/study/QuecPythonSub/
            - 音频开发:
                - QuecPython Audio模块开发: study/zh-cn/study/QuecPythonSub/Audio.md
                - QuecPython 录制音频: study/zh-cn/study/QuecPythonSub/
                - QuecPython TTS模块开发: study/zh-cn/study/QuecPythonSub/TTS.md
            - 总线开发:
                - QuecPython GPIO及IO中断开发: study/zh-cn/study/QuecPythonSub/GPIO.md
                - QuecPython UART开发: study/zh-cn/study/QuecPythonSub/UART.md
                - QuecPython I2C总线开发: study/zh-cn/study/QuecPythonSub/IIC.md
                - QuecPython PWM开发: study/zh-cn/study/QuecPythonSub/PWM.md
                - QuecPython ADC采样开发: study/zh-cn/study/QuecPythonSub/ADC.md
                - QuecPython SPI总线开发: study/zh-cn/study/QuecPythonSub/
            - 外设调试:
                - QuecPython SPI Nor Flash调试流程: study/zh-cn/study/QuecPythonSub/
                - QuecPython LCD调试流程: study/zh-cn/study/QuecPythonSub/
                - QuecPython Sensor调试流程: study/zh-cn/study/QuecPythonSub/
                - QuecPython 摄像头调试流程: study/zh-cn/study/QuecPythonSub/
                - QuecPython SD卡调试流程: study/zh-cn/study/QuecPythonSub/  
        - QuecPython 无线网络应用开发: study/zh-cn/study/index.md
        - QuecPython 网络应用开发: study/zh-cn/study/index.md
        - QuecPython 云服务: study/zh-cn/study/index.md
        - QuecPython 小实验: 
            - 总线:
                - 跑马灯实验: study/zh-cn/study/QuecPythonTest/LED.md
                - 蜂鸣器实验: study/zh-cn/study/QuecPythonTest/buzzer.md
                - 按键输入实验: study/zh-cn/study/QuecPythonTest/button.md
                - 串口实验: study/zh-cn/study/QuecPythonTest/uart.md
                - 外部中断实验: study/zh-cn/study/QuecPythonTest/External_interrupt.md
                - 独立看门狗实验: study/zh-cn/study/QuecPythonTest/WDT.md
                - 定时器中断实验: study/zh-cn/study/QuecPythonTest/timer.md
                - PWM 输出实验: study/zh-cn/study/QuecPythonTest/PWM.md
                - 待机唤醒实验: study/zh-cn/study/QuecPythonTest/PM.md
                - RTC 实验: study/zh-cn/study/QuecPythonTest/RTC.md
                - ADC 实验: study/zh-cn/study/QuecPythonTest/ADC.md
                - IIC 实验: study/zh-cn/study/QuecPythonTest/IIC.md
                - 录音实验: study/zh-cn/study/QuecPythonTest/record.md
                - 输入捕获实验: study/zh-cn/study/QuecPythonTest/GPIO.md
                - LCD 实验: study/zh-cn/study/QuecPythonTest/LCD.md
            - 传感器:
                - 内部温度传感器实验: study/zh-cn/study/QuecPythonTest/i2c_aht.md
                - 光敏传感器实验: study/zh-cn/study/QuecPythonTest/Photoresistor.md
                - 加速度传感器: study/zh-cn/study/QuecPythonTest/i2c_lis2dh.md
                - 步进电机驱动实验: study/zh-cn/study/QuecPythonTest/ebf_smd4805.md
                - 继电器实验: study/zh-cn/study/QuecPythonTest/relay.md 
        - QuecPython 应用编程框架: study/zh-cn/study/index.md
        - QuecPython Solution方案开发: study/zh-cn/study/index.md
        - QuecPython 产品开发及量产: study/zh-cn/study/QuecPythonMP.md
        - QuecPython FAQ&DEBUG: study/zh-cn/study/QuecPython FAQ&DEBUG/QuecPython_FAQ&Debug.pdf
        - 手把手教学: sbs/zh-cn/sbs/sbs.md


theme:
    name: readthedocs
    nav_style: light
    highlightjs: true
    navigation_depth: 6
    include_homepage_in_sidebar: false
    sticky_navigation: false
    #custom_dir: 'custom_theme/'
    hljs_languages:
        - yaml
        - python


plugins:
    - search

extra_css:
    - css/extra.css
  
extra_javascript:
    - js/extra.js